// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAstdT3x59rjn8tlivly6aaxvKvETS1UpE',
    appId: '1:364109652601:web:22c0f82528257b8bc6aaa8',
    messagingSenderId: '364109652601',
    projectId: 'aawnode',
    authDomain: 'aawnode.firebaseapp.com',
    storageBucket: 'aawnode.appspot.com',
    measurementId: 'G-694BEM07MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBepU9EIZKxy1mx5mHAKr7z2K_fIB22uRU',
    appId: '1:364109652601:android:04e599affb5811b5c6aaa8',
    messagingSenderId: '364109652601',
    projectId: 'aawnode',
    storageBucket: 'aawnode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfByxmtV6HdV4T5gOJK3okGUkGIofRD8',
    appId: '1:364109652601:ios:affe98f70f38bba2c6aaa8',
    messagingSenderId: '364109652601',
    projectId: 'aawnode',
    storageBucket: 'aawnode.appspot.com',
    iosClientId: '364109652601-g4jb96b8ctrbpdj0kcpjvjgvmmq395pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFfByxmtV6HdV4T5gOJK3okGUkGIofRD8',
    appId: '1:364109652601:ios:3e0b303f226daf7cc6aaa8',
    messagingSenderId: '364109652601',
    projectId: 'aawnode',
    storageBucket: 'aawnode.appspot.com',
    iosClientId: '364109652601-pdlb01asgmolj0mvctss8a3mb3v7gkro.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAaw.RunnerTests',
  );
}
